# https://github.com/arduino/arduino-lint-action

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'library.json'
      - 'library.properties'
  pull_request_target:

name: Arduino Library Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: arduino/arduino-lint-action@v2
        with:
          library-manager: update
          compliance: strict
          project-type: library
          verbose: true
